services:
  melly_finder:
    container_name: melly_finder
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./cache:/usr/app/cache/
    network_mode: "container:wireguard"
    env_file: '.env'
    command: "npm start"